黑石股票/Hei10.WebSite/Areas/Admin/Controllers/ConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Hei10.Core.Extensions;
using Hei10.Core.Utilities;
using Hei10.Domain.Enums;
using Hei10.Domain.Models;
using Hei10.Domain.Repositories;
using Hei10.Domain.ViewModels;
using Hei10.Web.Framework.Controllers;
using Hei10.Web.Framework.Security;

namespace Hei10.WebSite.Areas.Admin.Controllers
{
    public class ConsultController : AdminController
    {
        public IConsultRepository ConsultRepository { get; set; }
        public IConsultClassifyRepository ConsultClassifyRepository { get; set; }
        public ISysOperationLogRepository LogRepository { get; set; }

        [ValidatePage]
        public async Task<ActionResult> Index(string keyWord, long? consultClassifyId, string orderField = "Consult.CreateTime", string orderDirection = "desc", int pageCurrent = 1, int pageSize = 30)
        { 
            ViewBag.KeyWord = keyWord;
            ViewBag.ConsultClassifyId = consultClassifyId;
            ViewBag.Select = await ConsultClassifyRepository.GetListBySelectAsync();
            return PartialView("Index", ConsultRepository.GetPagedList(ConsultClassifyRepository.QueryUnDelete(), (keyWord??"").Trim(), consultClassifyId, orderField, orderDirection, pageCurrent, pageSize));
        }

        [ValidateButton(Buttons = SysButton.Browse, ActionName = "Index")]
        public async Task<ActionResult> Detail(long id)
        {
            var json = new JsonModel { message = "记录不存在了", statusCode = 300 };
            if (id < 1)
            {
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            var model = await ConsultRepository.GetUnDeleteByIdAsync(id);
            if (model == null)
            {
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            var consultClassify = await ConsultClassifyRepository.GetByIdAsync(model.ClassifyId);
            ViewBag.ConsultClassifyName = consultClassify == null ? "" : consultClassify.Title;
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateButton(Buttons = SysButton.Delete, ActionName = "Index")]
        public async Task<ActionResult> BatchDelete(string ids)
        { 
            var result = new JsonModel { statusCode = 300, message = "删除失败,记录不存在！", closeCurrent = false };
            if (string.IsNullOrEmpty(ids))
            {
                return Json(result);
            }
            var list = await ConsultRepository.BatchDeleteAsync(ids);
            if (list == null)
            {
                return Json(result);
            }
            var msg = string.Join(",", list.Select(m => m.Title).ToArray()).ToEllipsis(100);
            await LogRepository.Insert(TableSource.Consults, OperationType.Delete, string.Format("批量删除{0}等咨询", msg), ids);
            result.statusCode = 200;
            result.message = "删除成功！";
            return Json(result);
        }
    }
}

黑石股票/Hei10.WebSite/Controllers/ConsultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using JR.Domain.Enums;
using JR.Domain.Models;
using JR.Domain.Repositories;
using JR.Web.Framework.Controllers;
using JR.Web.Framework.Extensions;
using JR.WebSite.Models;

namespace JR.WebSite.Controllers
{
    public class ConsultController : FrontController
    {
        public IConsultRepository ConsultRepository { get; set; }
        public IConsultClassifyRepository ConsultClassifyRepository { get; set; }

        public async Task<ActionResult> Index(long id)
        {
            if (id < 1)
            {
                return RedirectTo404(Url.Home(), "找不到记录！");
            }
            var consultClassify = await ConsultClassifyRepository.GetEnableByIdAsync(id);
            if (consultClassify == null)
            {
                return RedirectTo404(Url.Home(), "找不到记录！");
            }
            return View(new ConsultModel { ClassifyId = id,ConsultClassifyTitle = consultClassify.Title , ConsultClassifyContents = consultClassify.Contents});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(ConsultModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var consult = new Consult();
            Mapper.Map(model, consult);
            consult.CommonStatus = CommonStatus.Enabled;
            await ConsultRepository.SaveAsync(consult);
            model.IsSucceed = true;
            return View(model);
        }
    }
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/Consult/Detail.cshtml
@model Hei10.Domain.Models.Consult

<div class="bjui-pageContent">
    <table class="table-bordered table-condensed table-hover" width="100%">
        <tbody>
            <tr>
                <td style="height: 60px;">
                    <label for="" class="control-label x85">姓名：</label>
                    @Html.Raw(Model.UserName)
                </td>
            </tr>
            <tr>
                <td style="height: 60px;">
                    <label for="" class="control-label x85">电子邮件：</label>
                    @Html.Raw(Model.Email)
                </td>
            </tr>
            <tr>
                <td style="height: 260px;">
                    <label for="" class="control-label x85">内容：</label>
                    @Html.Raw(Model.Contents)
                </td>
            </tr>  
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">取消</button></li> 
    </ul>
</div>

黑石股票/Hei10.WebSite/Areas/Admin/Views/Consult/Index.cshtml
@using Hei10.Core.Extensions
@model IPagedList<ConsultBizModel>
@{
    SysUser user = ViewBag.CurrUser;
    List<SelectListItem> select = ViewBag.Select;
}
<script type="text/javascript">
    $(function () { 
        $('.get-verification-token').attr({ "data-data": "__RequestVerificationToken=" + $('input[name="__RequestVerificationToken"]').val() });
    })
</script>

<div class="bjui-pageHeader">
    <form id="pagerForm" data-toggle="ajaxsearch" action="@Url.Action("Index")" method="get">
        <input type="hidden" name="pageSize" value="@Model.PageSize">
        <input type="hidden" name="pageCurrent" value="@Model.PageNumber">
        <input type="hidden" name="tabId" value="@Request["tabId"]" />
        <input type="hidden" name="orderField" value="@(Request["orderField"]??"Consult.CreateTime")">
        <input type="hidden" name="orderDirection" value="@(Request["orderDirection"]??"desc")">
        <div class="bjui-searchBar"> 
            <label>搜索关键词：</label><input type="text" id="keyWord" value="@(ViewBag.KeyWord)" name="keyWord" class="form-control" />&nbsp;
            <label>所属分类:</label>
            @Html.DropDownList("consultClassifyId", select, "请选择",new { @data_toggle = "selectpicker" })  
            <button type="submit" class="btn-default" data-icon="search">查询</button>&nbsp;
            <a class="btn btn-orange" href="javascript:;" onclick="$(this).navtab('reloadForm', true);" data-icon="undo">清空查询</a> 
            @if (user.HasButton(SysButton.Delete))
            {
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
                        <ul class="dropdown-menu right" role="menu">
                            <li><a href="@Url.Action("BatchDelete", "Consult")" class="get-verification-token" data-toggle="doajaxchecked" data-confirm-msg="确定要删除选中项吗？" data-idname="ids" data-group="ids">删除选中</a></li>
                        </ul>
                    </div>
                </div>
            }
        </div>
    </form>
</div>
<div class="bjui-pageContent tableContent">
    <table data-toggle="tablefixed" data-width="100%" data-nowrap="true">
        <thead>
        <tr>
            <th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th> 
            <th data-order-field="Consult.UserName">姓名</th> 
            <th data-order-field="Consult.Email">电子邮件</th>
            <th data-order-field="Consult.CreateTime">咨询时间</th>
            <th width="100">操作</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr data-id="@(item.Consult.Id)">
                <td><input type="checkbox" name="ids" data-toggle="icheck" value="@(item.Consult.Id)"></td> 
                <td>@item.Consult.UserName</td> 
                <td>@item.Consult.Email</td>
                <td>@item.Consult.CreateTime.ToDisplayDateTime()</td>
                <td>
                    @if (user.HasButton(SysButton.Browse))
                    {
                        <a href="@Url.Action("Detail", new {id = item.Consult.Id})" class="btn btn-green" data-toggle="navtab" data-width="800" data-height="400" data-id="consult-detail" data-reload-warn="本页已有打开的内容，确定将刷新本页内容，是否继续？" data-title="@(item.Consult.Title)-详情">详情</a>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
@Html.AntiForgeryToken()
@{ Html.RenderPartial("_Footer_Pager",Model);}
 