黑石股票/Hei10.WebSite/Areas/Admin/Controllers/RecruitJobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Hei10.Core.Utilities;
using Hei10.Domain.Enums;
using Hei10.Domain.Models;
using Hei10.Domain.Repositories;
using Hei10.Domain.Services;
using Hei10.Domain.ViewModels;
using Hei10.Web.Framework.Controllers;
using Hei10.Web.Framework.Security;
using Hei10.Domain.Entityframework;

namespace Hei10.WebSite.Areas.Admin.Controllers
{
    public class RecruitJobController : AdminController
    {
        public IRecruitJobRepository RecruitJobRepository { get; set; }
        public ISysOperationLogRepository LogRepository { get; set; }

        [ValidatePage]
        public ActionResult Index(string name,string orderField, string orderDirection, int pageCurrent = 1, int pageSize = 30)
        {
            ViewBag.name = name;
            var list = RecruitJobRepository.GetPagedList(pageCurrent, pageSize, orderField, orderDirection,name);
            return PartialView(list);
        }

        [ValidateButton(Buttons = SysButton.Delete, ActionName = "Index")]
        [HttpPost]
        public async Task<ActionResult> BatchDelete(string ids)
        {
            var result = new JsonModel { statusCode = 300, message = "删除失败,记录不存在！", closeCurrent = false };
            if (string.IsNullOrEmpty(ids))
            {
                return Json(result);
            }
            var arr = StringUtility.ConvertToBigIntArray(ids, ',');
            if (arr == null || !arr.Any())
            {
                return Json(result);
            }
            var idString = string.Join(",", arr);
            await RecruitJobRepository.BatchDeleteAsync(idString);
            result.statusCode = 200;
            result.message = "删除成功！";
            return Json(result);
        }

        [ValidateButton(Buttons = SysButton.Edit, ActionName = "Index")]
        public async Task<ActionResult> Edit(long id = 0)
        {
            RecruitJob model;
            if (id > 0)
            {
                model = await RecruitJobRepository.GetByIdAsync(id);
                if (model == null)
                {
                    var json = new JsonModel { message = "记录不存在了", statusCode = 300 };
                    return Json(json, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                model = DbFactory.CreateRecruitJob();
                model.WorkDuty = "1."+ Environment.NewLine + "2."+ Environment.NewLine+"3.";
                model.Requirement= "1." + Environment.NewLine + "2." + Environment.NewLine + "3.";
            }
            return PartialView(model);
        }

        [ValidateButton(Buttons = SysButton.Edit, ActionName = "Index")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(RecruitJob model)
        {
            var result = new JsonModel();
            // 数据有误
            if (!ModelState.IsValid)
            {
                result.GetError(ModelState);
                return Json(result);
            }

            var operationType = OperationType.Insert;
            var operationTitle = "添加招聘职位";
            if (model.Id > 0)
            {
                var adPos = await RecruitJobRepository.GetByIdAsync(model.Id);
                if (adPos == null)
                {
                    result.message = "记录不存在了";
                    return Json(result);
                }
                operationType = OperationType.Update;
                operationTitle = "修改招聘职位";
            }
            await RecruitJobRepository.SaveAsync(model);
            await LogRepository.Insert(TableSource.RecruitJob, operationType, operationTitle, model.Id);
            result.Data = model;
            result.message = "保存成功！";
            return Json(result);
        }
    }
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/RecruitJob/Edit.cshtml
@using Hei10.Core.Extensions
@using Hei10.Core.Utilities
@using Hei10.Domain.Enums
@using Hei10.Web.Framework.Extensions
@model RecruitJob
<script type="text/javascript">
    var tabId = '@Request["tabId"]';
    function button_callback(json) {
        if (json.Error) {
            for (var i = 0; i < json.Error.length; i++) {
                $('#' + json.Error[i].Key).next('span').html('<span class="msg-box n-right" style="" for="' + json.Error[i].Value + '"><span class="msg-wrap n-error" role="alert" style="left: 0px; opacity: 1;"><span class="n-arrow"><b>◆</b><i>◆</i></span><span class="glyphicon glyphicon-remove-circle" style="top: -1px; font-size: 14px; vertical-align: middle;"></span><span class="n-msg">' + json.Error[i].Value + '</span></span></span></span>').show();
            }
        } else {
            $(this)
                .bjuiajax('ajaxDone', json) // 信息提示
                .navtab('closeCurrentTab')
                .navtab('switchTab', tabId)
                .navtab('reloadForm',false, tabId);
        }

    }
</script>
@using (Html.BeginForm("Edit", "RecruitJob", FormMethod.Post, new { @data_toggle = "validate", @data_alertmsg = "false", @data_callback = "button_callback" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_Edit_Hidden_Base")
    <div class="bjui-pageContent">
        <table class="table-bordered table-condensed table-hover" width="100%">
            <tbody>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Name, new { @class = "control-label x85" })
                        @Html.TextBoxFor(m => m.Name, new { @class = "input-lg w500", @data_rule = "required;length[~50]" })
                        @Html.ValidationMessageFor(m => m.Name)
                        必填，最多50个字符。
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.WorkDuty, new { @class = "control-label x85" })
                        @Html.Raw(Html.TextAreaFor(m => m.WorkDuty, 18, 60, null))
                        @Html.ValidationMessageFor(m => m.WorkDuty)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Requirement, new { @class = "control-label x85" })
                        @Html.TextAreaFor(m => m.Requirement, 18, 60, null)
                        @Html.ValidationMessageFor(m => m.Requirement)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Sort, new { @class = "control-label x85" })
                        @Html.TextBoxFor(m => m.Sort, new { @size = "20", @data_rule = "required;digits;" })
                        @Html.ValidationMessageFor(m => m.Sort)
                        必填，数字越小越靠前
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="bjui-pageFooter">
        <ul>
            <li><button type="button" class="btn-close" data-icon="close">取消</button></li>
            <li><button type="submit" class="btn-default" data-icon="save">保存</button></li>
        </ul>
    </div>
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/RecruitJob/Index.cshtml
@using Hei10.Web.Framework.Extensions
@model IPagedList<RecruitJob>
@{
    string name = ViewBag.name;
    SysUser user = ViewBag.CurrUser;
    string tabId = Request["tabId"];
}
<script type="text/javascript">
    function delete_callback(json) {
        $(this)
            .bjuiajax('ajaxDone', json) // 信息提示
            .navtab('refresh', '');
    }
</script>
<div class="bjui-pageHeader">
    <form id="pagerForm" data-toggle="ajaxsearch" action="@Url.Action("Index")" method="post">
        <input type="hidden" name="pageSize" value="@Model.PageSize">
        <input type="hidden" name="pageCurrent" value="@Model.PageNumber">
        <input type="hidden" name="tabId" value="@tabId">
        <input type="hidden" name="orderField" value="@Request["orderField"]">
        <input type="hidden" name="orderDirection" value="@Request["orderDirection"]">
        <div class="bjui-searchBar">
            <label>标题：</label><input type="text" value="@name" name="name" class="form-control" size="15">
            <a class="btn btn-orange" href="javascript:;" data-toggle="reloadsearch" data-clear-query="true" data-icon="undo">清空查询</a>
            <button type="submit" class="btn-default" data-icon="search">查询</button>&nbsp;
            @if (user.HasButton(SysButton.Edit))
            {
                <a href="@Url.Action("Edit",new {tabId})" class="btn btn-green" data-toggle="navtab" data-id="recruitjob-edit">添加</a>
            }
            @if (user.HasButton(SysButton.Delete))
            {
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
                        <ul class="dropdown-menu right" role="menu">
                            <li><a href="@Url.Action("BatchDelete", "RecruitJob")" data-toggle="doajaxchecked" data-confirm-msg="确定要删除选中项吗？" data-idname="ids" data-group="ids" data-callback="delete_callback">删除选中</a></li>
                        </ul>
                    </div>
                </div>
            }
        </div>
    </form>
</div>
<div class="bjui-pageContent tableContent">
    <table data-toggle="tablefixed" data-width="100%">
        <thead>
            <tr>
                <th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
                <th data-order-field="Name" align="center">名称</th>
                <th data-order-field="Sort" align="center">排序</th>
                <th data-order-field="CreateTime" align="center">创建时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@(item.Id)">
                    <td width="26"><input type="checkbox" name="ids" data-toggle="icheck" value="@(item.Id)"></td>
                    <td>@item.Name</td>
                    <td>@item.Sort</td>
                    <td>@item.CreateTime.ToDisplayDateTime()</td>
                    <td>
                        @if (user.HasButton(SysButton.Edit))
                        {
                                 <a href="@Url.Action("Edit", new { item.Id,tabId })" class="btn btn-blue" data-toggle="navtab" data-id="recruitjob-edit">修改</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter">
    <div class="pages">
        <span>每页&nbsp;</span>
        <div class="selectPagesize">
            <select data-toggle="selectpicker" data-toggle-change="changepagesize">
                <option value="30">30</option>
                <option value="60">60</option>
                <option value="120">120</option>
                <option value="150">150</option>
            </select>
        </div>
        <span>&nbsp;条，共 @(Model.TotalItemCount) 条</span>
    </div>
    <div class="pagination-box" data-toggle="pagination" data-total="@(Model.TotalItemCount)" data-page-size="@Model.PageSize" data-page-current="@Model.PageNumber">
    </div>
</div>