黑石股票/Hei10.WebSite/Areas/Admin/Controllers/ConsultClassifyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Hei10.Core.Extensions;
using Hei10.Domain.Enums;
using Hei10.Domain.Models;
using Hei10.Domain.Repositories;
using Hei10.Domain.Services;
using Hei10.Domain.ViewModels;
using Hei10.Web.Framework.Controllers;
using Hei10.Web.Framework.Security;
using Hei10.WebSite.Areas.Admin.Models;

namespace Hei10.WebSite.Areas.Admin.Controllers
{
    public class ConsultClassifyController : AdminController
    {
        public IConsultClassifyRepository ConsultClassifyRepository { get; set; }
        public ISysOperationLogRepository LogRepository { get; set; }

        public ActionResult Index(string keyWord, string orderField, string orderDirection, int pageCurrent = 1, int pageSize = 30)
        {
            ViewBag.KeyWord = keyWord; 
            return PartialView("Index", ConsultClassifyRepository.GetPagedList((keyWord ?? "").Trim(), orderField, orderDirection, pageCurrent, pageSize));
        }

        [ValidateButton(Buttons = SysButton.Edit, ActionName = "Index")]
        public async Task<ActionResult> Edit(string navtabId, long id = 0)
        {
            var model = new ConsultClassifyModel();
            if (id > 0)
            {
                var consultClassify = await ConsultClassifyRepository.GetByIdAsync(id);
                if (consultClassify == null)
                {
                    var json = new JsonModel { message = "记录不存在了", statusCode = 300 };
                    return Json(json, JsonRequestBehavior.AllowGet);
                }
                Mapper.Map(consultClassify, model);
            }
            return PartialView(model);
        }


        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [ValidateButton(Buttons = SysButton.Edit, ActionName = "Index")]
        public async Task<ActionResult> Edit(ConsultClassifyModel model)
        {
            var json = new JsonModel(); 
            // 数据有误
            if (!ModelState.IsValid)
            {
                json.GetError(ModelState);
                return Json(json);
            }
            var operationType = OperationType.Insert;
            var operationTitle = "添加咨询分类信息";
            ConsultClassify consultClassify = null;
            if (model.Id > 0)
            {
                consultClassify = await ConsultClassifyRepository.GetByIdAsync(model.Id);
                if (consultClassify == null)
                {
                    json.message = "记录不存在了";
                    return Json(json);
                }
                operationType = OperationType.Update;
                operationTitle = "修改咨询分类信息";
            }
            else
            {
                consultClassify = new ConsultClassify();
            }
            Mapper.Map(model, consultClassify);
            consultClassify.CommonStatus = CommonStatus.Enabled;
            await ConsultClassifyRepository.SaveAsync(consultClassify);
            await LogRepository.Insert(TableSource.ConsultClassifies, operationType, operationTitle, consultClassify.Id); 
            return Json(json);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateButton(Buttons = SysButton.Delete, ActionName = "Index")]
        public async Task<ActionResult> BatchDelete(string ids)
        {
            var result = new JsonModel { statusCode = 300, message = "删除失败,记录不存在！", closeCurrent = false };
            if (string.IsNullOrEmpty(ids))
            {
                return Json(result);
            }
            var list = await ConsultClassifyRepository.BatchDeleteAsync(ids);
            if (list == null)
            {
                return Json(result);
            }
            var msg = string.Join(",", list.Select(m => m.Title).ToArray()).ToEllipsis(100);
            await LogRepository.Insert(TableSource.ConsultClassifies, OperationType.Delete, string.Format("批量删除{0}等咨询分类", msg), ids);
            result.statusCode = 200;
            result.message = "删除成功！";
            return Json(result);
        }
    }
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/ConsultClassify/Edit.cshtml
@model Hei10.WebSite.Areas.Admin.Models.ConsultClassifyModel
<script type="text/javascript"> 
    var tabId = '@Request["tabId"]';
    function consultClassify_callback(json) {
        if (json.Error) {
            for (var i = 0; i < json.Error.length; i++) {
                $('#' + json.Error[i].Key).next('span').html('<span class="msg-wrap n-error" role="alert" style="left: 0px; opacity: 1;"><span class="n-arrow"><b>◆</b><i>◆</i></span><span class="glyphicon glyphicon-remove-circle" style="top: -1px; font-size: 14px; vertical-align: middle;"></span><span class="n-msg">' + json.Error[i].Value + '</span></span></span>').show();
            }
        } else {
            $(this)
                .bjuiajax('ajaxDone', json) // 信息提示
                .navtab('closeCurrentTab') //关闭当前窗口
                .navtab('switchTab', tabId) // 刷新列表页
                .navtab('reloadForm', false, tabId);
        }

    }
</script>
@using (Html.BeginForm("Edit", "ConsultClassify", FormMethod.Post, new { @data_toggle = "validate", @data_alertmsg = "false", @data_callback = "consultClassify_callback" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="bjui-pageContent">
        <table class="table-bordered table-condensed table-hover" width="100%">
            <tbody> 
                <tr>
                    <td>
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.Title)：</label>
                        @Html.TextBoxFor(m => m.Title, new { @class = "input-lg w500", @data_rule = "required;length[~100]" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.Contents)：</label>
                        @Html.TextAreaFor(m => m.Contents, new { cols = "60", rows = "10", @data_rule = "required;length[~500]" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.Sort)：</label>
                        @Html.TextBoxFor(m => m.Sort, new { @class = "input-lg w500", @data_rule = "required;digits;" })
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="bjui-pageFooter">
        <ul>
            <li><button type="button" class="btn-close" data-icon="close">取消</button></li>
            <li><button type="submit" class="btn-default" data-icon="save">保存</button></li>
        </ul>
    </div>
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/ConsultClassify/Index.cshtml
@model IPagedList<Hei10.Domain.Models.ConsultClassify>
@{
    SysUser user = ViewBag.CurrUser;
}
<script type="text/javascript">
    $('.get-verification-token').attr({ "data-data": "__RequestVerificationToken=" + $('input[name="__RequestVerificationToken"]').val() }); 
</script>
<div class="bjui-pageHeader">
    <form id="pagerForm" data-toggle="ajaxsearch" action="@Url.Action("Index")" method="GET">
        <input type="hidden" name="pageSize" value="@Model.PageSize">
        <input type="hidden" name="pageCurrent" value="@Model.PageNumber">
        <input type="hidden" name="tabId" value="@Request["tabId"]" />
        <input type="hidden" name="orderField" value="@Request["orderField"]">
        <input type="hidden" name="orderDirection" value="@Request["orderDirection"]">
        <div class="bjui-searchBar">
            <label>搜索关键词：</label><input type="text" id="keyWord" value="@(ViewBag.KeyWord)" name="keyWord" class="form-control" />&nbsp; 
            <button type="submit" class="btn-default" data-icon="search">查询</button>&nbsp;
            <a class="btn btn-orange" href="javascript:;" onclick="$(this).navtab('reloadForm', true);" data-icon="undo">清空查询</a>
            @if (user.HasButton(SysButton.Add))
            {
                <a href="@Url.Action("Edit",new { tabId = Request["tabId"]})" class="btn btn-green" data-toggle="navtab" data-id="consultClassify-edit" data-reload-warn="本页已有打开的内容，确定将刷新本页内容，是否继续？" data-title="添加管理员信息">添加</a>
            } 
            @if (user.HasButton(SysButton.Delete))
            {
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
                        <ul class="dropdown-menu right" role="menu"> 
                            @if (user.HasButton(SysButton.Delete))
                            { 
                                <li><a href="@Url.Action("BatchDelete", "ConsultClassify")" class="get-verification-token" data-toggle="doajaxchecked" data-confirm-msg="确定要删除选中项吗？" data-idname="ids" data-group="ids">删除选中</a></li>
                            }
                        </ul>
                    </div>
                </div>
            }
        </div>
    </form>
</div>
<div class="bjui-pageContent tableContent">
    <table data-toggle="tablefixed" data-width="100%" data-nowrap="true">
        <thead>
            <tr>
                <th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>
                <th data-order-field="Title">标题</th>
                <th data-order-field="Sort">排序</th> 
                <th data-order-field="CreateTime">发布时间</th>
                <th data-order-field="CreateUserName">发布人</th>
                <th width="180">操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@(item.Id)">
                    <td><input type="checkbox" name="ids" data-toggle="icheck" value="@(item.Id)"></td>
                    <td>@item.Title</td>
                    <td>@item.Sort</td>
                    <td>@item.CreateTime.ToDisplayDateTime()</td>
                    <td>@item.CreateUserName</td>
                    <td>
                        @if (user.HasButton(SysButton.Edit))
                        {
                            <a href="@Url.Action("Edit", new {id = item.Id,tabId = Request["tabId"]})" class="btn btn-green" data-toggle="navtab" data-id="consultClassify-edit" data-reload-warn="本页已有打开的内容，确定将刷新本页内容，是否继续？" data-title="编辑-@(item.Title)">编辑</a>
                        }
                        @if (user.HasButton(SysButton.Delete))
                        {
                            <a href="@Url.Action("BatchDelete", "ConsultClassify", new {ids = item.Id})" class="btn btn-red get-verification-token" data-toggle="doajax" data-confirm-msg="确定要删除该行信息吗？">删除</a>
                        }
                        <a href="@Url.Consult(item.Id)" class="btn btn-orange" target="_blank">发布咨询</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@Html.AntiForgeryToken()
@{ Html.RenderPartial("_Footer_Pager", Model);}