黑石股票/Hei10.WebSite/Areas/Admin/Controllers/UCenterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Hei10.Core.Utilities;
using Hei10.Domain.Enums;
using Hei10.Domain.Models;
using Hei10.Domain.Repositories;
using Hei10.Domain.Services;
using Hei10.Domain.ViewModels;
using Hei10.Web.Framework.Controllers;
using Hei10.Web.Framework.Security;
using Hei10.WebSite.Areas.Admin.Models;

namespace Hei10.WebSite.Areas.Admin.Controllers
{
    public class UCenterController : AdminController
    {
        public IUsersRepository UsersRepository { get; set; }
        public ISysOperationLogRepository LogRepository { get; set; }
        public IAttachmentSvc AttachmentSvc { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        #region //修改密码
        public async Task<ActionResult> ModifyPwd()
        {
            var model = new ModifyPwdModel();
            var user = await UsersRepository.GetByIdAsync(User.UserInfo.UserId);
            if (user == null)
            {
                var json = new JsonModel { message = "记录不存在了", statusCode = 300 };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModifyPwd(ModifyPwdModel model)
        {
            var result = new JsonModel();
            var user = await UsersRepository.GetByIdAsync(User.UserInfo.UserId);
            if (user == null)
            {
                result.statusCode = 300;
                result.message = "该条数据不存在，请刷新重试！";
                return Json(result);
            }
            //原密码不正确
            if (!user.Password.Equals(HashUtils.HashPasswordWithSalt(model.OldPwssword, user.PasswordSalt)))
            {
                ModelState.AddModelError("OldPwssword", "原密码输入有误，请重新输入！");
            }
            if (!ModelState.IsValid)
            {
                result.GetError(ModelState);
                return Json(result);
            }
            if (!string.IsNullOrEmpty(model.Password))
            {
                user.PasswordSalt = HashUtils.GenerateSalt();
                user.Password = HashUtils.HashPasswordWithSalt(model.Password, user.PasswordSalt);
            }
            await LogRepository.Insert(TableSource.Users, OperationType.Update, "修改密码", user.Id);
            await UsersRepository.SaveAsync(user);
            result.Data = user;
            result.message = "保存成功！";
            return Json(result);
        }


        #endregion

        #region //修改用户信息
        public async Task<ActionResult> ModifyInfo()
        {
            var user = await UsersRepository.GetByIdAsync(User.UserInfo.UserId);
            var model = Mapper.Map<Users, AdminModel>(user);
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModifyInfo(AdminModel model)
        {
            ModelState.Remove("Password");
            ModelState.Remove("PasswordConfirm");
            var result = new JsonModel();
            // 数据有误
            if (!ModelState.IsValid)
            {
                result.GetError(ModelState);
                return Json(result);
            }
            var oldModel = await UsersRepository.GetByIdAsync(User.UserInfo.UserId);
            if (oldModel == null)
            {
                result.statusCode = 300;
                result.message = "该条数据不存在，请刷新重试！";
                return Json(result);
            }
            oldModel = Mapper.Map(model, oldModel);
            await UsersRepository.SaveAsync(oldModel);
            await AttachmentSvc.BoundAttachment(model.Id, model.HeadImg);
            //插入日志
            await LogRepository.Insert(TableSource.Users, OperationType.Update, "修改个人资料", oldModel.Id);
            result.Data = model;
            result.message = "保存成功！";
            return Json(result);
        }
        #endregion
    }
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/UCenter/ModifyInfo.cshtml
@using Hei10.Core.Extensions
@using Hei10.Core.Utilities
@using Hei10.Domain.Enums
@using Hei10.Web.Framework.Extensions
@model AdminModel
<script type="text/javascript">
    function doc_upload_success(file, data) {
        var json = $.parseJSON(data);
        $(this).bjuiajax('ajaxDone', json);
        if (json[BJUI.keys.statusCode] == BJUI.statusCode.ok) {
            $('#HeadImg').val(json.filePath);
            $('#doc_span_pic').html('已上传图片：<img src="' + json.imgPath + '" width="100">');
        }
    }
    function user_callback(json) {
        if (json.Error) {
            for (var i = 0; i < json.Error.length; i++) {
                $('#' + json.Error[i].Key).next('span').html('<span class="msg-box n-right" style="" for="' + json.Error[i].Value + '"><span class="msg-wrap n-error" role="alert" style="left: 0px; opacity: 1;"><span class="n-arrow"><b>◆</b><i>◆</i></span><span class="glyphicon glyphicon-remove-circle" style="top: -1px; font-size: 14px; vertical-align: middle;"></span><span class="n-msg">' + json.Error[i].Value + '</span></span></span></span>').show();
            }
        } else {
            doSetUserName($('#RealName').val());
            $(this)
                .bjuiajax('ajaxDone', json) // 信息提示
                .dialog('closeCurrent') //关闭当前
                .dialog('refresh', "");

        }

    }
</script>
@using (Html.BeginForm("ModifyInfo", "UCenter", FormMethod.Post, new { @data_toggle = "validate", @data_alertmsg = "false", @data_callback = "user_callback", @data_confirmMsg = "确定提交吗？" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.CommonStatus)
    @Html.HiddenFor(m => m.LoginName)
    <div class="bjui-pageContent">
        <table class="table-bordered table-condensed table-hover" width="100%">
            <tbody>
                <tr>
                    <td>
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.RealName)：</label>
                        @Html.TextBoxFor(m => m.RealName, new { @class = "input-lg w500", @data_rule = "required;length[~50]" })
                    @Html.ValidationMessageFor(m => m.RealName)
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.Remark)：</label>
                        @Html.TextAreaFor(m => m.Remark, new { cols = "60", rows = "10", @data_rule = "required;length[~250]" })
                        @Html.ValidationMessageFor(m => m.Remark)
                    </td>
                </tr>
                <tr>
                    <td class="h40">
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.Gender)：</label>
                        <input type="radio" name="Gender" id="Gender-radio1" value="@(Gender.Male)" data-toggle="icheck" @(Model.Gender == Gender.Male ? "checked=checked" : "") data-rule="checked" data-label="@(Gender.Male.GetDescriotion())">
                        <input type="radio" name="Gender" id="Gender-radio2" value="@(Gender.Female)" data-toggle="icheck" @(Model.Gender == Gender.Female ? "checked=checked" : "") data-label="@(Gender.Female.GetDescriotion())">
                        @Html.ValidationMessageFor(m => m.Gender)
                    </td>
                </tr>
                <tr>
                    <td class="h60">
                        <label for="" class="control-label x85">@Html.DisplayNameFor(m => m.HeadImg)：</label>
                        <div style="display:inline-block; vertical-align:middle;">
                            <div id="doc_pic_up" data-toggle="upload" data-uploader="@Url.Action("BatchUpload","Attachment",new { src = TableSource.Users })"
                                 data-file-size-limit="1024000000"
                                 data-file-type-exts="*.jpg;*.png;*.gif;*.mpg"
                                 data-multi="false"
                                 data-on-upload-success="doc_upload_success"
                                 data-icon="cloud-upload"></div>
                            @Html.HiddenFor(m => m.HeadImg)
                            @Html.ValidationMessageFor(m => m.HeadImg)
                        </div>
                        <span id="doc_span_pic">
                            @if (!string.IsNullOrEmpty(Model.HeadImg))
                            {
                                <img src="@Url.ThumbUrl(Model.HeadImg, "100x100")" alt="" width="100" style="margin-top: 10px;" />
                            }
                        </span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="bjui-pageFooter">
        <ul>
            <li><button type="button" class="btn-close" data-icon="close">取消</button></li>
            <li><button type="submit" class="btn-default" data-icon="save">保存</button></li>
        </ul>
    </div>
}

黑石股票/Hei10.WebSite/Areas/Admin/Views/UCenter/ModifyPwd.cshtml
@model ModifyPwdModel
<script>

    function button_callback(json) {
        if (json.Error) {
            for (var i = 0; i < json.Error.length; i++) {
                $('#' + json.Error[i].Key).next('span').html('<span class="msg-box n-right" style="" for="' + json.Error[i].Value + '"><span class="msg-wrap n-error" role="alert" style="left: 0px; opacity: 1;"><span class="n-arrow"><b>◆</b><i>◆</i></span><span class="glyphicon glyphicon-remove-circle" style="top: -1px; font-size: 14px; vertical-align: middle;"></span><span class="n-msg">' + json.Error[i].Value + '</span></span></span></span>').show();
            }
        } else {
            $(this)
            .bjuiajax('ajaxDone', json) // 信息提示
            .dialog('closeCurrent');
        }
    };
</script>
<div class="bjui-pageContent">
    <form action="@Url.Action("ModifyPwd")" class="pageForm" data-callback="button_callback" data-toggle="validate" data-alertmsg="false">
        @Html.AntiForgeryToken()
        <table class="table table-condensed table-hover">
            <tbody>
                <tr>
                    <td colspan="2" align="center"><h3>修改密码</h3></td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.OldPwssword, new { @class = "control-label x90" })
                        @Html.PasswordFor(m => m.OldPwssword, new Dictionary<string, object> { { "size", 20 }, { "data-rule", "required" } })
                        @Html.ValidationMessageFor(m => m.OldPwssword)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.Password, new { @class = "control-label x90" })
                        @Html.PasswordFor(m => m.Password, new Dictionary<string, object> { { "size", 20 }, { "data-rule", "required;length(6~16)" } })
                        @Html.ValidationMessageFor(m => m.Password)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(m => m.PasswordConfirm, new { @class = "control-label x90" })
                        @Html.PasswordFor(m => m.PasswordConfirm, new Dictionary<string, object> { { "size", 20 }, { "data-rule", "required;match(Password)" }, { "data-msg-match", "两次输入的密码不一致" } })
                        @Html.ValidationMessageFor(m => m.PasswordConfirm)
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close">关闭</button></li>
        <li><button type="submit" class="btn-default">保存</button></li>
    </ul>
</div>